import { BaseTool, createToolCollection } from "../client";
import {
  getMultiBalance,
  getTokenBalance,
  getTokenList,
  getTransactions,
  getInternalTransactions,
  getPendingTransactions,
  getTokenTransfers,
  getNftTransfers,
  getBlockReward,
  getBlockCountdown,
  getBlockNumberByTime,
  getLatestBlockNumber,
  getTransactionInfo,
  getTransactionReceiptStatus,
  getTransactionError,
  getContractABI,
  getContractSource,
  getContractCreation,
  getContracts,
  getLogs,
  getTokenInfo,
  getTokenHolders,
  getTokenSupply,
  getNativeSupply,
  getNativePrice,
  getTotalFees,
} from "./tools";

export function blockscoutTools(): BaseTool[] {
  return createToolCollection([
    getMultiBalance,
    getTokenBalance,
    getTokenList,
    getTransactions,
    getInternalTransactions,
    getPendingTransactions,
    getTokenTransfers,
    getNftTransfers,
    getBlockReward,
    getBlockCountdown,
    getBlockNumberByTime,
    getLatestBlockNumber,
    getTransactionInfo,
    getTransactionReceiptStatus,
    getTransactionError,
    getContractABI,
    getContractSource,
    getContractCreation,
    getContracts,
    getLogs,
    getTokenInfo,
    getTokenHolders,
    getTokenSupply,
    getNativeSupply,
    getNativePrice,
    getTotalFees,
  ]);
}
